<a href="https://colab.research.google.com/github/goelnaman66/py/blob/master/Fake_news_classifier_using_lstm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Word Embedding**

---

one hot representation-
suppose there are 10000 words in a dictionary and we want to represent man in the form of one hot representation. let the word man comes at 5000 position in the dictionary. then we will a get a vector of 10000 elements where at 5000 position we will get 1 and rest at all other positions we will get 0.

it is very difficult to process this representation. it has a sparse matrix and it is very very long.
word embedding relates the words to different features. This solves the problem of higher dimension and sparse matrix.

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent = ['the glass of milk', 'the glass of juice', 'the cup of tea', 'I am a good boy', 'I am a good developer', 'understand the meaning of words','your videos are good']

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
#defining vocabulary size
voc_size=10000

In [5]:
#one hot representation
onehot_repr= [one_hot(words,voc_size) for words in sent]
print(onehot_repr)

[[1476, 6018, 5522, 9299], [1476, 6018, 5522, 7145], [1476, 5335, 5522, 9460], [3094, 9660, 7087, 2945, 1738], [3094, 9660, 7087, 2945, 9207], [5946, 1476, 6741, 5522, 4606], [7006, 6432, 5978, 2945]]


In [6]:
#word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_len = 8
embedded_docs = pad_sequences(onehot_repr,padding='pre',maxlen=sent_len)                 #padding
print(embedded_docs)

[[   0    0    0    0 1476 6018 5522 9299]
 [   0    0    0    0 1476 6018 5522 7145]
 [   0    0    0    0 1476 5335 5522 9460]
 [   0    0    0 3094 9660 7087 2945 1738]
 [   0    0    0 3094 9660 7087 2945 9207]
 [   0    0    0 5946 1476 6741 5522 4606]
 [   0    0    0    0 7006 6432 5978 2945]]


In [9]:
dim = 10

In [10]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_len))
model.compile('adam','mse')

In [11]:
print(model.predict(embedded_docs))

[[[-0.03241712 -0.0060586   0.011621   -0.03802124  0.03491274
    0.02898614 -0.01883304  0.04531899  0.01475023  0.03203214]
  [-0.03241712 -0.0060586   0.011621   -0.03802124  0.03491274
    0.02898614 -0.01883304  0.04531899  0.01475023  0.03203214]
  [-0.03241712 -0.0060586   0.011621   -0.03802124  0.03491274
    0.02898614 -0.01883304  0.04531899  0.01475023  0.03203214]
  [-0.03241712 -0.0060586   0.011621   -0.03802124  0.03491274
    0.02898614 -0.01883304  0.04531899  0.01475023  0.03203214]
  [-0.01941458 -0.0099613   0.03426493  0.01854772  0.01687957
    0.01700613 -0.02723798  0.02780083  0.02317324  0.02412896]
  [ 0.00888895 -0.00967622  0.00861341  0.02431149  0.02689458
   -0.01756133  0.04165791  0.00171471 -0.01455456  0.03140109]
  [-0.01031067 -0.01561983 -0.00157914 -0.02607865 -0.0094296
    0.00961578 -0.00421933  0.03660882  0.04618435  0.04334379]
  [-0.04434557  0.02212913 -0.01753862 -0.04200346  0.01030074
    0.00368569 -0.00326905  0.02328179 -0.0259970

In [12]:
embedded_docs[0]  #first sentence

array([   0,    0,    0,    0, 1476, 6018, 5522, 9299], dtype=int32)

In [13]:
# 0 will be converted to 10 features/dim vector
# 0 will be converted to 10 features/dim vector
# 0 will be converted to 10 features/dim vector
# 0 will be converted to 10 features/dim vector
# 5945 will be converted to 10 features/dim vector
# 2999 will be converted to 10 features/dim vector
# 3777 will be converted to 10 features/dim vector
# 1072 will be converted to 10 features/dim vector
print(model.predict(embedded_docs[0]))



[[[-0.03241712 -0.0060586   0.011621   -0.03802124  0.03491274
    0.02898614 -0.01883304  0.04531899  0.01475023  0.03203214]]

 [[-0.03241712 -0.0060586   0.011621   -0.03802124  0.03491274
    0.02898614 -0.01883304  0.04531899  0.01475023  0.03203214]]

 [[-0.03241712 -0.0060586   0.011621   -0.03802124  0.03491274
    0.02898614 -0.01883304  0.04531899  0.01475023  0.03203214]]

 [[-0.03241712 -0.0060586   0.011621   -0.03802124  0.03491274
    0.02898614 -0.01883304  0.04531899  0.01475023  0.03203214]]

 [[-0.01941458 -0.0099613   0.03426493  0.01854772  0.01687957
    0.01700613 -0.02723798  0.02780083  0.02317324  0.02412896]]

 [[ 0.00888895 -0.00967622  0.00861341  0.02431149  0.02689458
   -0.01756133  0.04165791  0.00171471 -0.01455456  0.03140109]]

 [[-0.01031067 -0.01561983 -0.00157914 -0.02607865 -0.0094296
    0.00961578 -0.00421933  0.03660882  0.04618435  0.04334379]]

 [[-0.04434557  0.02212913 -0.01753862 -0.04200346  0.01030074
    0.00368569 -0.00326905  0.02328

In [14]:
from tensorflow.keras.layers import LSTM

fake news classifier using lstm

---



---



In [15]:
from tensorflow.keras.layers import Dense

In [16]:
import pandas as pd


In [17]:
df=pd.read_csv('/content/drive/MyDrive/train.csv')

In [18]:
df

id  ... label
0          0  ...     1
1          1  ...     0
2          2  ...     1
3          3  ...     1
4          4  ...     1
...      ...  ...   ...
20795  20795  ...     0
20796  20796  ...     0
20797  20797  ...     0
20798  20798  ...     1
20799  20799  ...     1

[20800 rows x 5 columns]

In [19]:
df=df.dropna()

In [20]:
df=df.reset_index()

In [21]:
X = df.drop('label',axis=1)

In [22]:
y=df['label']

In [23]:
X.shape

(18285, 5)

In [24]:
df.shape

(18285, 6)

In [25]:
import tensorflow as tf

In [26]:
tf.__version__

'2.5.0'

In [27]:
#vocabulary size
voc_size=5000

In [28]:
import nltk
import re
from nltk.corpus import stopwords

In [29]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [30]:
###datapreprocessing
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
messages=X.copy()

In [31]:
for i in range(0, len(messages)):
  
  review = re.sub('[^a-zA-Z]', ' ', messages['title'][i]) #substituting everything apart from a-z A-Z by blank space
  review= review.lower()                                 #lowering of words
  review = review.split()
  review= [ps.stem(word) for word in review if not word in stopwords.words('english')]
  review= ' '.join(review)
  corpus.append(review)

In [32]:
m=messages['title'][0]
print(m)
m=re.sub('[^a-zA-Z]',' ',m)
print(m)

House Dem Aide: We Didn’t Even See Comey’s Letter Until Jason Chaffetz Tweeted It
House Dem Aide  We Didn t Even See Comey s Letter Until Jason Chaffetz Tweeted It


In [33]:
m=m.lower()
print(m)
m=m.split()
print(m)

house dem aide  we didn t even see comey s letter until jason chaffetz tweeted it
['house', 'dem', 'aide', 'we', 'didn', 't', 'even', 'see', 'comey', 's', 'letter', 'until', 'jason', 'chaffetz', 'tweeted', 'it']


In [34]:
m= [ps.stem(word) for word in m if not word in stopwords.words('english')]
print(m)

['hous', 'dem', 'aid', 'even', 'see', 'comey', 'letter', 'jason', 'chaffetz', 'tweet']


In [35]:
m = ' '.join(m)
print(m)

hous dem aid even see comey letter jason chaffetz tweet


In [36]:
corpus[:5]

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri']

In [37]:
#one hot representation
onehot_repr= [one_hot(words,voc_size) for words in corpus]
print(onehot_repr[0])

[526, 833, 1374, 4614, 4538, 4455, 4736, 4704, 984, 2316]


In [38]:
sent_len = 20
embedded_docs = pad_sequences(onehot_repr,padding='pre',maxlen=sent_len)                 #padding
print(embedded_docs)

[[   0    0    0 ... 4704  984 2316]
 [   0    0    0 ...  960 3664  956]
 [   0    0    0 ... 1084 4944  997]
 ...
 [   0    0    0 ... 2406 1512 3695]
 [   0    0    0 ... 2668  294 4446]
 [   0    0    0 ... 4385 3006 3837]]


In [39]:
len(embedded_docs)

18285

In [40]:
dim=40
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_len))
model.add(LSTM(100))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 20, 40)            200000    
_________________________________________________________________
lstm (LSTM)                  (None, 100)               56400     
_________________________________________________________________
dense (Dense)                (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


Training the model

In [41]:
X=np.array(embedded_docs)
y=np.array(y)

In [42]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X,y,test_size=0.33,random_state=42)


In [43]:
model.fit(X_train,y_train, validation_data=(X_test,y_test), epochs=10, batch_size=64)

Epoch 1/10
192/192 [==============================] - 10s 10ms/step - loss: 0.3357 - accuracy: 0.8392 - val_loss: 0.1973 - val_accuracy: 0.9142
Epoch 2/10
192/192 [==============================] - 2s 8ms/step - loss: 0.1391 - accuracy: 0.9459 - val_loss: 0.2032 - val_accuracy: 0.9114
Epoch 3/10
192/192 [==============================] - 2s 8ms/step - loss: 0.0977 - accuracy: 0.9638 - val_loss: 0.2244 - val_accuracy: 0.9145
Epoch 4/10
192/192 [==============================] - 2s 8ms/step - loss: 0.0632 - accuracy: 0.9778 - val_loss: 0.2778 - val_accuracy: 0.9118
Epoch 5/10
192/192 [==============================] - 2s 9ms/step - loss: 0.0406 - accuracy: 0.9869 - val_loss: 0.2652 - val_accuracy: 0.9117
Epoch 6/10
192/192 [==============================] - 2s 8ms/step - loss: 0.0263 - accuracy: 0.9926 - val_loss: 0.3517 - val_accuracy: 0.9069
Epoch 7/10
192/192 [==============================] - 2s 8ms/step - loss: 0.0164 - accuracy: 0.9953 - val_loss: 0.4337 - val_accuracy: 0.9037
Epoc

Predicting the results

In [44]:
y_pred=model.predict_classes(X_test)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [45]:
y_pred[1]

array([0], dtype=int32)

In [46]:
from sklearn.metrics import confusion_matrix

In [47]:
confusion_matrix(y_test,y_pred)

array([[3112,  307],
       [ 246, 2370]])

In [48]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.9083678541839271

In [49]:
#adding dropout layer
from tensorflow.keras.layers import Dropout
dim=40
model1 = Sequential()
model1.add(Embedding(voc_size, dim, input_length=sent_len))
model1.add(Dropout(0.3))
model1.add(LSTM(100))
model1.add(Dropout(0.3))
model1.add(Dense(1, activation='sigmoid'))
model1.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 20, 40)            200000    
_________________________________________________________________
lstm (LSTM)                  (None, 100)               56400     
_________________________________________________________________
dense (Dense)                (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [50]:
model1.fit(X_train,y_train, validation_data=(X_test,y_test), epochs=10, batch_size=64)

Epoch 1/10
192/192 [==============================] - 3s 10ms/step - loss: 0.3545 - accuracy: 0.8297 - val_loss: 0.2008 - val_accuracy: 0.9105
Epoch 2/10
192/192 [==============================] - 2s 8ms/step - loss: 0.1521 - accuracy: 0.9400 - val_loss: 0.1990 - val_accuracy: 0.9168
Epoch 3/10
192/192 [==============================] - 2s 8ms/step - loss: 0.1147 - accuracy: 0.9562 - val_loss: 0.2149 - val_accuracy: 0.9137
Epoch 4/10
192/192 [==============================] - 2s 8ms/step - loss: 0.0910 - accuracy: 0.9660 - val_loss: 0.2195 - val_accuracy: 0.9127
Epoch 5/10
192/192 [==============================] - 2s 8ms/step - loss: 0.0753 - accuracy: 0.9739 - val_loss: 0.2681 - val_accuracy: 0.9070
Epoch 6/10
192/192 [==============================] - 2s 8ms/step - loss: 0.0563 - accuracy: 0.9802 - val_loss: 0.2842 - val_accuracy: 0.9109
Epoch 7/10
192/192 [==============================] - 2s 8ms/step - loss: 0.0464 - accuracy: 0.9839 - val_loss: 0.3229 - val_accuracy: 0.9001
Epoch

In [51]:
y_pred1=model1.predict_classes(X_test)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [52]:
accuracy_score(y_test, y_pred1)

0.9095277547638774